<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class buscar_categoria extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'refeições']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'banquete']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'almoço']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'jantar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'café da manhã']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'alimentação']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'alimento']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'tempero']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'vegetais']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'sabor']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'sal']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'açucar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'doce']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'amargo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'comida']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'molho']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'azedo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'pão']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'restaurante']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'prato']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'lanche']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'pizza']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'pizzaria']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'condimentos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'refeição']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'merenda']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'bolacha']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'chocolate']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'fome']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'frutas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'carne']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'suino']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'bovino']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'peixe']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'frutos do mar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'saladas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'prato-feito']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'cardápio']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'vitamina']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'dieta']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'nutrição']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'colher']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'garfo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'faca']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'cozinha']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'sopa']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'proteína']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'nutrir']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'nutrientes']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 2,'pchaves' => 'cozinhar']);

        DB::table('buscar_categoria')->insert(['id_categoria' => 3,'pchaves' => 'modelos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 3,'pchaves' => 'empregos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 3,'pchaves' => 'financiadoras']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 3,'pchaves' => 'Bancarias']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 3,'pchaves' => 'digital']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 3,'pchaves' => 'publicidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 3,'pchaves' => 'privada']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 3,'pchaves' => 'publica']);

        DB::table('buscar_categoria')->insert(['id_categoria' => 4,'pchaves' => 'plantação']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 4,'pchaves' => 'defensivos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 4,'pchaves' => 'produtos agricolas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 4,'pchaves' => 'tratores']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 4,'pchaves' => 'solo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 4,'pchaves' => 'biologo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 4,'pchaves' => 'cerca']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 4,'pchaves' => 'frutas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 4,'pchaves' => 'carne']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 4,'pchaves' => 'floriculturas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 4,'pchaves' => 'biocombustíveis']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 4,'pchaves' => 'têxtil']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 4,'pchaves' => 'madeira']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 4,'pchaves' => 'casas']);

        DB::table('buscar_categoria')->insert(['id_categoria' => 5,'pchaves' => 'imoveis']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 5,'pchaves' => 'quartos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 5,'pchaves' => 'motel']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 5,'pchaves' => 'carros']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 5,'pchaves' => 'motos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 5,'pchaves' => 'eventos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 5,'pchaves' => 'festas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 5,'pchaves' => 'mão de obra']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 5,'pchaves' => 'peças']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 5,'pchaves' => 'equipamentos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 5,'pchaves' => 'locação']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 5,'pchaves' => 'obrigação']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 5,'pchaves' => 'prestação de serviço']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 5,'pchaves' => 'contrato']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 5,'pchaves' => 'locação']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 5,'pchaves' => 'alugar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 5,'pchaves' => 'inquilino']);

        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'mecanica']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'venda']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'compra']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'aluguel']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'peças']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'carros']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'motos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'garagem']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'auto eletrica']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'retifica']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'funilaria']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'motores']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'hidráulicos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'motores']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'marítimos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'borracheiro']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'pneus']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'rodas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'alarme']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'troca de oleo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'lavagem']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'lubrificação']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'veículos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'automotores']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 6,'pchaves' => 'Motores elétricos']);
        
        DB::table('buscar_categoria')->insert(['id_categoria' => 7,'pchaves' => 'salão de Beleza']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 7,'pchaves' => 'cosmeticos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 7,'pchaves' => 'mulher']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 7,'pchaves' => 'homem']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 7,'pchaves' => 'criança']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 7,'pchaves' => 'batom']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 7,'pchaves' => 'maquiagem']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 7,'pchaves' => 'sombrancelha']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 7,'pchaves' => 'lapis de olho']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 7,'pchaves' => 'acessórios']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 7,'pchaves' => 'smalte']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 7,'pchaves' => 'shampoo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 7,'pchaves' => 'condicionador']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 7,'pchaves' => 'cabelereira']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 7,'pchaves' => 'manicure']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 7,'pchaves' => 'pedicure']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 7,'pchaves' => 'chapinha']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 7,'pchaves' => 'creme']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 7,'pchaves' => 'hidratante']);

        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'roupas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'designer']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'moda']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'sapatos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'lingerie']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'terno']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'camisa']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'calça']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'jeans']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'fraque']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'gravata']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'sapatilhas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'tamanco']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'salto alto']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'sapateiro']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'costureira']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'vestido']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'cinto']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'fivela']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'abotoadura']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'têxtil']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'cores']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'tecidos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'couro']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'sola']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'brincos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'bijuteria']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'poliéster']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'polipropileno']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Náilon']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Poliamida']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Acrílico']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Elastanos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Lycra']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Raiom']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Viscose']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Hidrofilidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Hidrofobilidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Finura']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Elasticidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Resistência']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Tecido plano']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Tecido cala']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Tecido Jacquard']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Tecido de veludo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'algodão']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'adamascados']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Brocado']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Cashemere']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Cetim']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Chamalote']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Chintz']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Seda']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Shantung']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Panamá']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Voil']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Costura']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Chevrom']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Crepe']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Crepom']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Jeans']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Lona']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Petit pois']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Popeline']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'Principe de galles']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 8,'pchaves' => 'cimento']);

        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'tijolo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'areia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'terra']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'pedras']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'matérias de construção']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'hidráulica']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'torneira']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'elétrica']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'fios']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'pedreiros']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'pintor']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'ferramentas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'telhas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'portas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'janelas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'portões']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'alarme']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'abraçadeira']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'acabamento']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'acetinado']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'agregado']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'andaime']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'arquiteto']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'azulejo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'balcão']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'betoneira']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'concreto']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'eletricista']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'EPI']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'laje']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'mármore']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'marceneiro']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'paisagismo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'terraplanagem']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 9,'pchaves' => 'viga']);

        DB::table('buscar_categoria')->insert(['id_categoria' => 10,'pchaves' => 'cinema']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 10,'pchaves' => 'teatro']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 10,'pchaves' => 'eventos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 10,'pchaves' => 'festas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 10,'pchaves' => 'rodeio']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 10,'pchaves' => 'shows']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 10,'pchaves' => 'Jardins Botânicos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 10,'pchaves' => 'zoológicos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 10,'pchaves' => 'parques']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 10,'pchaves' => 'Reservas Ecológicas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 10,'pchaves' => 'livrarias']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 10,'pchaves' => 'museus']);

        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'investimento']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'dolar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'real']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'bancos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'financiamento']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'lotericas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'bolsa de valores']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'economia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'ativos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'título']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'negociação']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'minério']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'produto']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'matéria-prima']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'comércio']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'econômico']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'acumular']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'aforrar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'ajuntar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'amealhar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'cumular']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'entesourar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'forrar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'guardar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'juntar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'mealhar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'reunir']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'controlar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'governar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'moderar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'poupar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'esperdiçar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'entornar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'estafar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'dilapidar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'esbaldir']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'desaproveitar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'resgastar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'malbaratear']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'espatifar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'larguear']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'estragar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'esbanjar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'desperdiçar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'desarranjar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'malbaratar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'podesbaratarupar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'delapidar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'gualdir']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'gastar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'consumir']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'esgotar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'dissipar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'despender']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'expender']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'desembolsar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'aquietar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'apaziguar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'sossegar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'perder']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'prodigar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'empanturrar-se']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'malgastar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'espalhar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'disseminar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'dispersar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'prodigalizar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'reajuste de preços']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 11,'pchaves' => 'inflação']);

        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'compra']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'venda']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'aluguel']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'casas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'apartamentos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'terrenos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'casa']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'armazém']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'botoeira']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'classe']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'dinastia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'domicílio']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'edificação']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'edifício']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'lar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'loja']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'mansão']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'morada']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'penates']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'prédio']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'propriedade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'residência']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'teto']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'vivenda']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'apartado']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'domínio']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'autoridade bem bens']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'canga']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'dependência']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'dominação']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'estado']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'império']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'habitat']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'esconderijo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'guarida']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'valhacouto']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'estância']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'cobertura']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'estuque']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'chácara']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'povoação']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'povoamento']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'quartel']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'tabernáculo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 12,'pchaves' => 'aldeamento']);

        DB::table('buscar_categoria')->insert(['id_categoria' => 13,'pchaves' => 'metalurgica']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 13,'pchaves' => 'serralheria']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 13,'pchaves' => 'construtora']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 13,'pchaves' => 'distribuidora']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 13,'pchaves' => 'transportadora']);

        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'processos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'civil']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'criminal']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'trabalhista']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'juiz']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'advogado']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'fórum']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'carteira de trabalho']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'contrato']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'procon']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'correção']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'verdade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'legitimidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'direito']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'competência']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'correição']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'imparcialidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'sensatez']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'virtude']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'certo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'empertigado']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'empinado']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'endireitado']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'espigado']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'faculdade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'foro']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'honesto']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'honrado']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'imposto']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'íntegro']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'justiça']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'justo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'lei']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'mando']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'prerrogativa']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'privilégio']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'probo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'razão']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'regalia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'regrado']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'reportado']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'reto']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'taxa']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'tributo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'vertical']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'equanimidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'moderação']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'prudência']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'retidão']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'equidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'igualdade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'alçada']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'foral']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'instancia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'juízo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'jurisdição']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'pensão']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'gládio']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'combate']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'espada']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'farca']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'poder']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'punhal']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'isenção']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'neutralidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'razão']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'retidão']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'integridade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'onisciência']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'inteireza']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'legalidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'lisura']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'seriedade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'severidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'acrimônia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'apertamento']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'aspereza']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'austeridade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'circunspeção']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'dureza']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'gravidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'incomplacência']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'inflexibilidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'rigidez']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'rigor']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'rigorismo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 14,'pchaves' => 'retitude']);

        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'informática']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'equipamentos de tecnologia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'suprimentos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'celular']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'smartphone']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'tablet']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'gps']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'software']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'programas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'sistemas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'access point']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'acesso dedicado']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'acessibilidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'activex']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'administrador da base']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'inovador']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'redes sociais']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'redes comerciais']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'aplicações']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'dados']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'administrador de rede']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'aplicações']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'aplicativo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'biotecnologia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'cabo óptico']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'bluetooth']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'conectividade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'chats']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'e-business']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'inteligência artificial']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'inovação']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'marketing']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 15,'pchaves' => 'online']);

        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'propaganda']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'internet']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'telefonia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'celular']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'anuncio']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'telões']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'cartazes']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'folhetos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'comunicação']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'youtube']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'social']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'network']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'televisão']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'imprensa']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'rádio']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'jornalismo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'divulgação']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'público-alvo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'notícia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'entretenimento']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'letras']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'letreiros']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'placas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'publicidade virtual']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'carros de som']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'motos de som']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'faixas comemorativas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'faixas promocionais']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'folder']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'merchandising']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'Business to Business']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 16,'pchaves' => 'telemarketing']);

        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'Deus']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'Jesus']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'Nossa Senhora']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'Xango']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'Iemanja']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'Orun']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'Ogun']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'Cosme Damião']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'São Pedro']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'São Paulo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'São Jorge']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'Cruz']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'livros']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'biblia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'guias']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'velas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'igrejas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'centros']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'casas de oração']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'crença']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'doutrina']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'princípios']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'convicção']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'crédito']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'fé']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'religião']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'culto']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'adoração']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'civilizado']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'cultivado']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'erudito']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'homenagem']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'idolatria']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'ilustrado']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'instruído']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'liturgia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'veneração']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'devoção']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'afeição']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'dedicação']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'fervor']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'piedade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'ciência']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'credo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'disciplina']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'ensinamento']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'ensino']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'erudição']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'escola']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'filosofia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'instrução']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'devoção']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'palavra']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'rito']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'saber']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'seita']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'teoria']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'testemunho']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'clemência']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'confiança']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'misericórdia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'compaixão']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'dizimar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'santidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'valores']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'comiseração']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'enternecimento']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'remissão']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'cerimonial']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'diligência']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'ética']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 17,'pchaves' => 'unidos']);

        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'Planos de saúde']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'Planos odontologicos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'doenças']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'clinicas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'médicos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'dentistas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'plantonistas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'hospital']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'ambulancia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'Farmácias de Manipulação']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'Farmácias']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'Drogarias']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'Farmácias Homeopáticas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'Farmácias Veterinárias']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'Laboratórios']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'Laboratórios Clínicos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'Laboratórios de Anatomia Patológica']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'Citológica']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'Artigos Médicos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'Ortopédicos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'salubridade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'sanidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'bem estar']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'convicção']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'desejos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'higidez']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'saudável']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'força']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'eficácia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'energia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'potência']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'robustez']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'vigor']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'virilidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'vivacidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'robusteza']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'robustidão']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'lucidez']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'doença']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'insalubridade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'insanidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'incredulidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'morbidez']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'mórbido']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'doente']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'paciente']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'insano']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'impotência']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'invalidez']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'debilidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'insânia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'desatino']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'fraqueza']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'demência']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'loucura']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 18,'pchaves' => 'fragilidade']);

        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'segurança']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'cercas elétricas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'câmeras']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'guardas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'policia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'delegacia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'seguros']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'alarmes']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'estabilidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'assesto']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'afirmação']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'certeza']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'abonação']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'caução']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'abono']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'cautela']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'depósito']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'fiança']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'garantia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'penhor']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'afirmativa']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'convicção']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'evidência']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'exatidão']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'firmeza']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'justeza']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'confiança']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'audácia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'crédito']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'esperança']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'consolidação']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'equilíbrio']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'fixidez']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'fortaleza']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'proteção']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'guarda']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'abrigo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'anteparo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'arrecadação']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'custódia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'depositário']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'escolta']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'patrulha']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'piquete']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'precaução']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'prevenção']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'proteção']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'sentinela']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'tutela']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'vigia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'vigilância']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'vigilante']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'resistência']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'segureza']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'asseguramento']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'salvamento']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'seguridade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'responsabilidade']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'salvaguarda']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 19,'pchaves' => 'asseguração']);

        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'ônibus']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'motos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'táxi']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'van']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'viatura']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'ambulância']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'avião']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'helicópteros']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'barcos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'navio']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'bicicleta']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'Trem']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'comboio']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'carro']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'Micro-ônibus']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'caminhão']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'bonde']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'eléctrico']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'metrô']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'metropolitano']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'motocicleta']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'bicicleta']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'submarino']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'barca']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'balsa']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'barco']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'navio']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'hovercraft']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'jetski']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'canoa']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'lancha']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'góndola']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'transatlântico']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'avião']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'helicóptero']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'balão']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'dirigível']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'jato']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 20,'pchaves' => 'avioneta']);

        DB::table('buscar_categoria')->insert(['id_categoria' => 21,'pchaves' => 'financeira']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 21,'pchaves' => 'produção']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 21,'pchaves' => 'pública']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 21,'pchaves' => 'materiais']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 21,'pchaves' => 'marketing']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 21,'pchaves' => 'pessoas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 21,'pchaves' => 'sistêmica']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 21,'pchaves' => 'Sistemas de Informação']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 21,'pchaves' => 'Sistemas e Métodos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 21,'pchaves' => 'Comércio Internacional']);

        DB::table('buscar_categoria')->insert(['id_categoria' => 23,'pchaves' => 'Cooperativas agropecuárias']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 23,'pchaves' => 'Cooperativas de consumo']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 23,'pchaves' => 'Cooperativas de crédito']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 23,'pchaves' => 'Cooperativas educacionais']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 23,'pchaves' => 'Cooperativas especiais']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 23,'pchaves' => 'Cooperativas habitacionais']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 23,'pchaves' => 'Cooperativas de infra-estrutura']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 23,'pchaves' => 'Cooperativas de produção']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 23,'pchaves' => 'Cooperativas de saúde']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 23,'pchaves' => 'Cooperativas de trabalho']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 23,'pchaves' => 'Cooperativas de transporte de cargas e passageiros']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 23,'pchaves' => 'Cooperativas de turismo e lazer']);
        
        DB::table('buscar_categoria')->insert(['id_categoria' => 26,'pchaves' => 'escolas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 26,'pchaves' => 'faculdades']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 26,'pchaves' => 'cursos']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 26,'pchaves' => 'idiomas']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 26,'pchaves' => 'inglês']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 26,'pchaves' => 'espanhol']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 26,'pchaves' => 'japonês']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 26,'pchaves' => 'italiano']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 26,'pchaves' => 'informática']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 26,'pchaves' => 'matemática']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 26,'pchaves' => 'português']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 26,'pchaves' => 'senac']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 26,'pchaves' => 'etec']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 26,'pchaves' => 'medicina']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 26,'pchaves' => 'biologia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 26,'pchaves' => 'historia']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 26,'pchaves' => 'física']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 26,'pchaves' => 'química']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 26,'pchaves' => 'infantil']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 26,'pchaves' => 'Segundo Grau']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 26,'pchaves' => 'profissionalizante']);

        DB::table('buscar_categoria')->insert(['id_categoria' => 28,'pchaves' => 'ongs']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 28,'pchaves' => 'entidades']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 28,'pchaves' => 'associações']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 28,'pchaves' => 'sindicato']);
        DB::table('buscar_categoria')->insert(['id_categoria' => 28,'pchaves' => 'organização']);
       
    }
}

