<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class subcategoria extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('subcategoria')->insert(['id_categoria' => 1,'subcategoria' => 'Sex Shopping']);
        DB::table('subcategoria')->insert(['id_categoria' => 1,'subcategoria' => 'Sexologia']);
        DB::table('subcategoria')->insert(['id_categoria' => 1,'subcategoria' => 'Moteis']);
        DB::table('subcategoria')->insert(['id_categoria' => 1,'subcategoria' => 'Drivers']);
        DB::table('subcategoria')->insert(['id_categoria' => 1,'subcategoria' => 'Casas Noturnas']);
        DB::table('subcategoria')->insert(['id_categoria' => 1,'subcategoria' => 'Casas de massagem']);
        DB::table('subcategoria')->insert(['id_categoria' => 1,'subcategoria' => 'Boates']);
        DB::table('subcategoria')->insert(['id_categoria' => 1,'subcategoria' => 'Acompanhantes']);

        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Varejões']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Suplementos alimentares']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Supermercados']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Sucos']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Sorveterias']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Salgados']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Rotisserie']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Restaurantes']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Queijos']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Pizzarias']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Peixarias']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Panificadoras']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Padarias']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Massas']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Lojas de Bebidas']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Lanchonetes']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Grelhados']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Gelo']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Frutos do mar']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Frigoríficos']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Frios']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Cozinha internacional']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Cozinha Industrial']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Cozinha Indiana']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Cozinha francesa']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Cozinha chinesa']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Cozinha árabe']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Cozinha alemã']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Churrasqueiras']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Churrascarias']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Choperias']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Chocolates']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Cestas de alimentos']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Camaras frigoríficas']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Casas de chá']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Cafés']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Buffet']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Bolos']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Bebidas']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Bares']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Balcões frigoríficos']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Balcões de refrigeração']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Artigos e equipamentos para lanchonetes']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Artigos e equipamentos para bares']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Artigos e equipamentos para restaurantes']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Artigos e equipamentos para churrasco']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Alimentos - Prontos']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Alimentos - Orgânicos']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Alimentos - Dietéticos']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Alimentos - Congelados']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Água Mineral']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Açougues']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Espetos']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Mercearias']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Self-Service']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Confeitarias']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Industria de Alimentação']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Pastelaria']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Pastel']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Espetinhos']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Hot Dog']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Cachorro Quente']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Serv Festa']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'cervejaria']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'cachaçaria']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Panqueca']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Produtos Orientais']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Casas de Suco']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Casas de Salgados']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Casa de Frios e Queijos']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Casa de Massas']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Distribuidor de Gelo']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Casa de Frios']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Distribuidor de Bebidas']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Café Expresso']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Casa de bolos e tortas']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Casa de carnes']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Churrasquinho']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Churros']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Creperia']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Croissanteria']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Cybercafé']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Food truck']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Fornecimento de refeições em marmita']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Frutas desidratadas']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Fábrica de Conservas']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Fábrica de gelo']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Loja de açaí']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Merenda escolar']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Pamonharia']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Peixaria']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Serviço de garçom']);
        DB::table('subcategoria')->insert(['id_categoria' => 2,'subcategoria' => 'Temakeria']);

        DB::table('subcategoria')->insert(['id_categoria' => 3,'subcategoria' => 'Propriedade Industrial']);
        DB::table('subcategoria')->insert(['id_categoria' => 3,'subcategoria' => 'Matrimoniais']);
        DB::table('subcategoria')->insert(['id_categoria' => 3,'subcategoria' => 'Viagens']);
        DB::table('subcategoria')->insert(['id_categoria' => 3,'subcategoria' => 'Serviços Portuários']);
        DB::table('subcategoria')->insert(['id_categoria' => 3,'subcategoria' => 'Relacionamentos']);
        DB::table('subcategoria')->insert(['id_categoria' => 3,'subcategoria' => 'Publicidade']);
        DB::table('subcategoria')->insert(['id_categoria' => 3,'subcategoria' => 'Modelos e Manequins']);
        DB::table('subcategoria')->insert(['id_categoria' => 3,'subcategoria' => 'Fomento']);
        DB::table('subcategoria')->insert(['id_categoria' => 3,'subcategoria' => 'Cobranças']);
        DB::table('subcategoria')->insert(['id_categoria' => 3,'subcategoria' => 'Compras']);
        DB::table('subcategoria')->insert(['id_categoria' => 3,'subcategoria' => 'Investimentos em Aplicações Financeiras']);
        DB::table('subcategoria')->insert(['id_categoria' => 3,'subcategoria' => 'Desenvolvimento Econômico']);
        DB::table('subcategoria')->insert(['id_categoria' => 3,'subcategoria' => 'Formatura']);

        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Abate de Bovinos']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Abate Halal']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Abate kosher']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Aditivos Alimentares na nutrição de Aves']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Administração de Pesca']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Agricultura']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Apicultura (Criação de Abelha)']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Aqüicultura (Organismos Aquaticos)']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Caprinocultura (Criação de Cabras)']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Carcinicultura (Criação de camarões)']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Castração de Bovinos']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Comportamento e Bem-Estar animal']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Criação de Búfalos']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Criação de Javalis']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Criação de Suínos']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Cultivo de Vieiras']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'cunicultura (Criação de Coelhos)']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Diagnóstico de Prenhez em Bovinos']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Elaboração de Projetos Zootécnicos']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Eqüideocultura (criação de cavalos)']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Escore Corporal']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Estrutiocultura (Criação de Avestruz)']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Gado de Leite - Sistemas de Ordenha']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Inseminação Artificial em Bovinos']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Inseminação Artificial em Tempo Fixo']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Insensibilização de animais de abate']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Instalações para Gado de Leite']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Manejo pré-abate de suínos']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Matérias primas da Nutrição Animal']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Matriz Reprodutora']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Ovinocultura (Criação de Carneiros)']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Pecuária']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Pecuária de Corte']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Pecuária Orgânica']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'piscicultura (Criação de peixes)']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Produção de bovinos em confinamento']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Produção in vitro de Embriões bovinos']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Rastreabilidade Bovina']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Sericicultura']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Silagem']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Sisbov']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Sistemas de Custos da Empresa Pecuária']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Sistemas de pastejo para bovinos']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Zootecnista']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'Estufas']);
        DB::table('subcategoria')->insert(['id_categoria' => 4,'subcategoria' => 'agropecuária']);

        DB::table('subcategoria')->insert(['id_categoria' => 5,'subcategoria' => 'de Andaimes']);
        DB::table('subcategoria')->insert(['id_categoria' => 5,'subcategoria' => 'de Aparelhos de Jogos Eletrônicos']);
        DB::table('subcategoria')->insert(['id_categoria' => 5,'subcategoria' => 'de Automóveis']);
        DB::table('subcategoria')->insert(['id_categoria' => 5,'subcategoria' => 'de Equipamentos Científicos']);
        DB::table('subcategoria')->insert(['id_categoria' => 5,'subcategoria' => 'de Equipamentos Médicos']);
        DB::table('subcategoria')->insert(['id_categoria' => 5,'subcategoria' => 'de Equipamentos Hospitalares']);
        DB::table('subcategoria')->insert(['id_categoria' => 5,'subcategoria' => 'de equipamentos de informática']);
        DB::table('subcategoria')->insert(['id_categoria' => 5,'subcategoria' => 'de Fitas de Vídeo,DVDs e Blu-Ray']);
        DB::table('subcategoria')->insert(['id_categoria' => 5,'subcategoria' => 'de Imóveis Próprios']);
        DB::table('subcategoria')->insert(['id_categoria' => 5,'subcategoria' => 'de Instrumentos Musicais']);
        DB::table('subcategoria')->insert(['id_categoria' => 5,'subcategoria' => 'de Móveis']);
        DB::table('subcategoria')->insert(['id_categoria' => 5,'subcategoria' => 'de Utensílios e Aparelhos de Uso Doméstico']);
        DB::table('subcategoria')->insert(['id_categoria' => 5,'subcategoria' => 'de Máquinas e Equipamentos Agrícolas']);
        DB::table('subcategoria')->insert(['id_categoria' => 5,'subcategoria' => 'de Máquinas e Equipamentos para Construção']);
        DB::table('subcategoria')->insert(['id_categoria' => 5,'subcategoria' => 'de Máquinas e Equipamentos para Escritório']);
        DB::table('subcategoria')->insert(['id_categoria' => 5,'subcategoria' => 'de Objetos do Vestuário']);
        DB::table('subcategoria')->insert(['id_categoria' => 5,'subcategoria' => 'Joias e Acessórios']);
        DB::table('subcategoria')->insert(['id_categoria' => 5,'subcategoria' => 'de Palcos e Coberturas']);
        DB::table('subcategoria')->insert(['id_categoria' => 5,'subcategoria' => 'de Roupas']);
        
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Aditivos']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Autoescolas']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Automóveis importados']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Autopeças']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Comércio por Atacado de Pneus e Câmaras']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Equipamentos elétricos']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Equipamentos eletrônicos']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Estacionamentos de Veículos']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Fabricação de Peças e Acessórios para Veículos']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Fabricação de veículos']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Funilária']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Garagens']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Locação de Automóveis']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Locação de Automóveis com Motorista']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Lubrificantes / Filtros']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Mecânicas']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Revendedoras de Veículos']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Seguros']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Socorro de automóveis']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Auto Elétrica']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Auto Mecânicas']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Borracharias']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Concessionárias']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Design Automotivo']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Despachantes']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Engates']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Gás Natural Veícular']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Troca de Óleo']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Implementos Rodoviarios']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Centro Automotivo']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Sons Automotivos']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Peças Automotivos']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Baterias']);
        DB::table('subcategoria')->insert(['id_categoria' => 6,'subcategoria' => 'Pneus e Rodas']);

        DB::table('subcategoria')->insert(['id_categoria' => 7,'subcategoria' => 'Aparelhos para estética']);
        DB::table('subcategoria')->insert(['id_categoria' => 7,'subcategoria' => 'Bronzeamento Artificial']);
        DB::table('subcategoria')->insert(['id_categoria' => 7,'subcategoria' => 'Cabelereira']);
        DB::table('subcategoria')->insert(['id_categoria' => 7,'subcategoria' => 'Cósmeticos']);
        DB::table('subcategoria')->insert(['id_categoria' => 7,'subcategoria' => 'Dermatologista']);
        DB::table('subcategoria')->insert(['id_categoria' => 7,'subcategoria' => 'Estética']);
        DB::table('subcategoria')->insert(['id_categoria' => 7,'subcategoria' => 'Esteticistas']);
        DB::table('subcategoria')->insert(['id_categoria' => 7,'subcategoria' => 'Fitness']);
        DB::table('subcategoria')->insert(['id_categoria' => 7,'subcategoria' => 'Limpeza de Pele']);
        DB::table('subcategoria')->insert(['id_categoria' => 7,'subcategoria' => 'Manicure']);
        DB::table('subcategoria')->insert(['id_categoria' => 7,'subcategoria' => 'Mascara/Hidratação Facial']);
        DB::table('subcategoria')->insert(['id_categoria' => 7,'subcategoria' => 'Massoterapia']);
        DB::table('subcategoria')->insert(['id_categoria' => 7,'subcategoria' => 'Salão de Beleza']);
        DB::table('subcategoria')->insert(['id_categoria' => 7,'subcategoria' => 'Perfumaria']);
        DB::table('subcategoria')->insert(['id_categoria' => 7,'subcategoria' => 'Perfumes, Cremes, Hidratante']);
        DB::table('subcategoria')->insert(['id_categoria' => 7,'subcategoria' => 'Hidratante']);
        DB::table('subcategoria')->insert(['id_categoria' => 7,'subcategoria' => 'Esmaltes']);

        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Agências de modelos e manequins']);
        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Alfaiates']);
        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Aluguel de Roupas']);
        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Artigos de Praia']);
        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Atacado de Tecidos']);
        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Venda de calçados']);
        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Camisetas promocionais']);
        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Confecção de Roupas']);
        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Confecção de Roupas Íntimas']);
        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Confecção de Roupas sob Medida']);
        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Costureiras']);
        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Curtimento/Preparações de Couro']);
        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Lojas de Vestuário']);
        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Peças de Vestuário']);
        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Peças de Vestuário sob Medida']);
        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Loja de Roupas Intímas']);
        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Loja de Roupas']);
        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Sapataria']);
        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Loja de calçados']);
        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Fitness']);
        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Esportes - Artigos e Equipamentos']);
        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Uniformes Esportivos']);
        DB::table('subcategoria')->insert(['id_categoria' => 8,'subcategoria' => 'Uniformes']);

        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Aluguel de Máquinas e Equipamentos']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Aparelhamento de Pedras para Construção']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Armações Metálicas para Construção']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Arquitetos']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Arquitetura']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Bombas hidráulicas']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Decoração de Interior']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Eletricista']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Empresas construtoras']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Encanamento']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Engenharia']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Engenheiros']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Extração e Britamento de Pedras']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Instalação Hidráulica, Sanitária e de Gás']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Lojas de Materiais de Construção']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Lojas de Materiais Hidráulicos']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Lojas de Material Elétrico']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Lojas de Tintas e Materiais para Pintura']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Mármores e Granitos(Atacado)']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Materiais de Construção (Atacado)']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Materiais p/ Construir']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Obras de Terraplenagem']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Pedreiros']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Pintores']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Serralheiros']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Transformadores elétricos']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Parafuso']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Ferramentas']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Soldagem']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Portões de Ferro']);
        DB::table('subcategoria')->insert(['id_categoria' => 9,'subcategoria' => 'Calhas']);

        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Agências de relacionamentos']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Agências de Viagens']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Aluguel de Palcos e Coberturas']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Artes Cênicas e Espetáculos']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Astrologia']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Atividades Esportivas']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Atividades Paisagísticas']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Bailes']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Balneários']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Banca de Jornais']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Bronzeamento artificial']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Caça e Pesca']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Camping']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Casas de Espetáculo']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Casas de Festas']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Casas Noturnas']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Centros Culturais']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Clubes Sociais e Esportivos']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Constr.de Instal. Esportivas/Recreativas']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Cursos e Idiomas']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Danceterias']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Discotecas']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Distribuidoras de filmes']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Estaleiros']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Eventos']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Calhas']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Feiras']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Filmagem de Festas e Eventos']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Galerias de Arte']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Jornais e Revistas']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Natação']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Parques Aquáticos']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Parques de Diversão']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Parques Temáticos']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Ponto turístico']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Produção Musical']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Produção Teatral']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Profissionais p/ Ativ. Artísticas']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Profissionais p/ Ativ. Culturais']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Salas de Cinema']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Salões de Dança']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Sauna']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Sebos']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Shoppings']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Shows']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Sorveterias']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Spas']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Turismo']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Video Locadoras']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Yoga']);
        DB::table('subcategoria')->insert(['id_categoria' => 10,'subcategoria' => 'Piscinas']);

        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Bancos']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Casas de câmbio']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Concessão de Crédito']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Consórcios']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Consultores Econômico/Financeiros']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Consultoria/Auditoria Contábil']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Consultoria/Auditoria Tributária']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Consultoria em Gestão Empresarial']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Contabilidade']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Contadores']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Cooperativas Centrais de Crédito']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Cooperativas de Crédito Mútuo']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Defesa do Consumidor']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Financeiras']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Seguros']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Seguros de Vida']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Seguros Saúde']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Sistema de venda de crédito']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Sociedades de Crédito']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Sociedades de Financiamento']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Sociedades de Investimento']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Analista Contabil']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Profissional do contabilista']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Contador']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Auditor']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Contador, Auditor']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Perito Contábil']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Analista Financeiro']);
        DB::table('subcategoria')->insert(['id_categoria' => 11,'subcategoria' => 'Gestor de Empresas']);

        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Água e esgotos']);
        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Aluguel de Imóveis Próprios']);
        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Asilos e Abrigos']);
        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Automação Predial']);
        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Automação Residencial']);
        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Casa e Jardim']);
        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Compra e Venda de Imóveis Próprios']);
        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Construção civil']);
        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Construção de Edifícios']);
        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Constr. de Estações/Redes de Energia Elétrica']);
        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Corretagem no Aluguel de Imóveis']);
        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Corretoras de Títulos e Valores Mobiliários']);
        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Corretores de imóveis']);
        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Empreendimentos imobiliários']);
        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Empresa de urbanização']);
        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Flats']);
        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Hospedagem']);
        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Hóteis']);
        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Imobiliárias']);
        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Pensões']);
        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Pintura de Edifícios']);
        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Pintura de Residências']);
        DB::table('subcategoria')->insert(['id_categoria' => 12,'subcategoria' => 'Pousadas']);

        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Açúcar e Álcool']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Artigos e equip. de refr. industrial']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Atividades de Apoio à Extração de Minerais']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Automação Industrial']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Climatização Industrial']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Coleta de Resíduos Perigosos']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Bombas e Compressores']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Café Torrado, Moído e Solúvel']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Calçados']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Cerveja, Chopp e Refrigerante']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Embalagens']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Esquadrias de Metal']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Estruturas Metálicas']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Estruturas Pré-Moldadas de Concreto Armado']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Estufas e Fornos Elétricos']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Máquinas e Equipamentos']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Produtos químicos']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Produtos Siderúrgicos e Metalúrgicos']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Refrigeradores']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Veículos Automotores']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Fundição de Ferro e Aço']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Máquinas e Equipamentos para Uso Industrial']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Metalurgia do Cobre']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Metalurgia e Siderurgia']);
        DB::table('subcategoria')->insert(['id_categoria' => 13,'subcategoria' => 'Reparação de Máquinas']);

        DB::table('subcategoria')->insert(['id_categoria' => 14,'subcategoria' => 'Advogados']);
        DB::table('subcategoria')->insert(['id_categoria' => 14,'subcategoria' => 'Advogados Civil']);
        DB::table('subcategoria')->insert(['id_categoria' => 14,'subcategoria' => 'Advogados Criminal']);
        DB::table('subcategoria')->insert(['id_categoria' => 14,'subcategoria' => 'Advogados Trabalhistas']);
        DB::table('subcategoria')->insert(['id_categoria' => 14,'subcategoria' => 'Agente de Propriedade Industrial']);
        DB::table('subcategoria')->insert(['id_categoria' => 14,'subcategoria' => 'Associações de Defesa de Direitos Sociais']);
        DB::table('subcategoria')->insert(['id_categoria' => 14,'subcategoria' => 'Atividades Auxiliares da Justiça']);
        DB::table('subcategoria')->insert(['id_categoria' => 14,'subcategoria' => 'Sociedades de direitos autorais']);

        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Aluguel de Aparelhos de Jogos Eletrônicos']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Aluguel de equipamentos de informática']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Casas de desenvolvimento de sistemas']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Consultoria em Tecnologia da Informação']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Cursos de Informática']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Desenvolvimento de App de Computador']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Equipamentos de Informática']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Estações e Redes de Telecomunicações']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Implantação de Redes']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Informática']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Jogos Eletrônicos']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Lan House']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Licenciamento de Programas de Computador']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Lojas de Informática']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Manutenção de Computadores/Periféricos']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Pesquisas tecnológicas']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Suporte Técnico em Tecnologia da Informação']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Telecomunicações']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Telecomunicações por Satélite']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Telefonia Móvel Celular']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Treinamento em Informática']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Cyber Cafés']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Desenvolvimento de Software - Assistencia Técnica - Vendas e Consultoria']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Venda de Cartuchos, Impressoras e Manutenção']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Cartuchos de Impressoras']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Manutenção de Impressoras']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Venda de Impressoras e Cartuchos']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Sistemas para automação comercial - Atacado e Varejo']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Desenvolvimento de Sistemas Web e Hospedagens de sites']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Analista de Sistemas']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Analista de Sistemas Junior']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Analista de Sistemas Pleno']);
        DB::table('subcategoria')->insert(['id_categoria' => 15,'subcategoria' => 'Analista de Sistemas Senior']);

        DB::table('subcategoria')->insert(['id_categoria' => 16,'subcategoria' => 'Agenciamento de Espaços para Publicidade']);
        DB::table('subcategoria')->insert(['id_categoria' => 16,'subcategoria' => 'Agências de Publicidade']);
        DB::table('subcategoria')->insert(['id_categoria' => 16,'subcategoria' => 'Atividades de Telecomunicações']);
        DB::table('subcategoria')->insert(['id_categoria' => 16,'subcategoria' => 'Brindes']);
        DB::table('subcategoria')->insert(['id_categoria' => 16,'subcategoria' => 'Carros de Som']);
        DB::table('subcategoria')->insert(['id_categoria' => 16,'subcategoria' => 'Catálogos']);
        DB::table('subcategoria')->insert(['id_categoria' => 16,'subcategoria' => 'Consultores de marketing']);
        DB::table('subcategoria')->insert(['id_categoria' => 16,'subcategoria' => 'Consultoria em Publicidade']);
        DB::table('subcategoria')->insert(['id_categoria' => 16,'subcategoria' => 'Desenvolvedores de WebSites']);
        DB::table('subcategoria')->insert(['id_categoria' => 16,'subcategoria' => 'Empresas de telemarketing']);
        DB::table('subcategoria')->insert(['id_categoria' => 16,'subcategoria' => 'Gráficas']);
        DB::table('subcategoria')->insert(['id_categoria' => 16,'subcategoria' => 'Impressão de Material Publicitário']);
        DB::table('subcategoria')->insert(['id_categoria' => 16,'subcategoria' => 'Impressão Digital']);
        DB::table('subcategoria')->insert(['id_categoria' => 16,'subcategoria' => 'Jornalistas']);
        DB::table('subcategoria')->insert(['id_categoria' => 16,'subcategoria' => 'Lojas de Equipamentos Telefonia/Comunicação']);
        DB::table('subcategoria')->insert(['id_categoria' => 16,'subcategoria' => 'Motos de Som']);
        DB::table('subcategoria')->insert(['id_categoria' => 16,'subcategoria' => 'Marketing Digital']);
        DB::table('subcategoria')->insert(['id_categoria' => 16,'subcategoria' => 'Audio Visual']);
        DB::table('subcategoria')->insert(['id_categoria' => 16,'subcategoria' => 'Fotografia']);
        DB::table('subcategoria')->insert(['id_categoria' => 16,'subcategoria' => 'Fotógrafos de Eventos']);
        
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Adventista']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Alquimia']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Budismo']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Candomblé']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Catolicismo']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Cientologia']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Esoterica']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Espiritismo']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Evangélico']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Hinduísmo']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Islamismo']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Judaísmo']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Maçonaria']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Messiânica']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Misticismo']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Mormom']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Hare Krishna']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Sannyasin de Osho Rajneesh']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Neopaganismo']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Protestante']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Satanismo']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Seicho-no-ie']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Taoísmo']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Testemunhas de Jeová']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Umbanda']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Wicca']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Xamanismo']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Xintoísmo']);
        DB::table('subcategoria')->insert(['id_categoria' => 17,'subcategoria' => 'Artigos Religiosos']);

        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Academias']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Acupuntura']);        
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Alergia e Imunologia']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Ambulatórios']);        
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Análises Clínicas']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Anatomia Patológica e Citologia']);        
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Andrologia e Urologia']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Anestesiologia']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Angiologia']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Aparelhos auditivos']);        
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Aparelhos para estética']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Assistência odontológica']);        
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Auxiliares de enfermagem']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Bancos de Sangue']);        
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Cardiologia']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Cirurgia Cardiovascular']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Cirurgia Geral']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Cirurgia Pediátrica']);        
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Cirurgia Plástica']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Cirurgia Torácica']);        
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Cirurgia Vascular']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Clínicas e Residências Geriátricas']);        
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Consultores hospitalares']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Cromoterapia']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Dentistas']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Dermatologia']);        
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Descontaminação']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Diagnóstico por Imagem']);        
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Diálise e Nefrologia']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Emergência']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Enfermeiras(os)']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Fabricação de remêdios Farmacêuticos']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Fabricação de remêdios Homeopáticos']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Farmácias de Manipulação']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Farmácias e Drogarias']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Farmácias Homeopáticas']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Farmácias Veterinárias']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Fisioterapeutas']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Gastroenterologia']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Ginecologia']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Hematologia']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Laboratórios Clínicos']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Laboratórios de Anatomia']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Laboratórios de Patológica']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Laboratórios de Citológica']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Medicina do Trabalho']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Neurocirurgia']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Neurologia']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Neurologia Pediátrica']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Nutricionistas']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Ortopedia e Traumatologia']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Otorrinolaringologia']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Pneumologia']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Postos de Saúde']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Pronto Socorro']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Psicanalistas']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Psicólogos']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Psiquiatria']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Quimioterapia']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Radiologista']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Reumatologia']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Tomografia']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Unidades Hospitalares para Urgências']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Odontologia']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'medicina diagnóstica']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Equipamentos Médicos']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Suplementos']);
        DB::table('subcategoria')->insert(['id_categoria' => 18,'subcategoria' => 'Piscinas']);

        DB::table('subcategoria')->insert(['id_categoria' => 19,'subcategoria' => 'Blindagem']);
        DB::table('subcategoria')->insert(['id_categoria' => 19,'subcategoria' => 'Acessórios para Segurança Pessoal']);
        DB::table('subcategoria')->insert(['id_categoria' => 19,'subcategoria' => 'Acessórios para Segurança Profissional']);
        DB::table('subcategoria')->insert(['id_categoria' => 19,'subcategoria' => 'Armas e Munições']);
        DB::table('subcategoria')->insert(['id_categoria' => 19,'subcategoria' => 'Empresas de segurança e vigilância']);
        DB::table('subcategoria')->insert(['id_categoria' => 19,'subcategoria' => 'Equipamentos de Segurança']);
        DB::table('subcategoria')->insert(['id_categoria' => 19,'subcategoria' => 'Monitoramento de Sistemas de Segurança']);
        DB::table('subcategoria')->insert(['id_categoria' => 19,'subcategoria' => 'Segurança']);
        DB::table('subcategoria')->insert(['id_categoria' => 19,'subcategoria' => 'Segurança do Trabalho']);
        DB::table('subcategoria')->insert(['id_categoria' => 19,'subcategoria' => 'Seguridade Social Obrigatória']);
        DB::table('subcategoria')->insert(['id_categoria' => 19,'subcategoria' => 'Vigilância e Segurança Privada']);

        DB::table('subcategoria')->insert(['id_categoria' => 20,'subcategoria' => 'Aeroporto']);
        DB::table('subcategoria')->insert(['id_categoria' => 20,'subcategoria' => 'Aviões']);
        DB::table('subcategoria')->insert(['id_categoria' => 20,'subcategoria' => 'Barcos']);
        DB::table('subcategoria')->insert(['id_categoria' => 20,'subcategoria' => 'Carreto']);
        DB::table('subcategoria')->insert(['id_categoria' => 20,'subcategoria' => 'Guinchos']);
        DB::table('subcategoria')->insert(['id_categoria' => 20,'subcategoria' => 'Guindastes']);
        DB::table('subcategoria')->insert(['id_categoria' => 20,'subcategoria' => 'Helicópteros']);
        DB::table('subcategoria')->insert(['id_categoria' => 20,'subcategoria' => 'Lanchas']);
        DB::table('subcategoria')->insert(['id_categoria' => 20,'subcategoria' => 'Moto Taxi']);
        DB::table('subcategoria')->insert(['id_categoria' => 20,'subcategoria' => 'Taxi']);
        DB::table('subcategoria')->insert(['id_categoria' => 20,'subcategoria' => 'Transporte Aéreo de Carga']);
        DB::table('subcategoria')->insert(['id_categoria' => 20,'subcategoria' => 'Transporte Escolar']);
        DB::table('subcategoria')->insert(['id_categoria' => 20,'subcategoria' => 'Transporte Ferroviário']);
        DB::table('subcategoria')->insert(['id_categoria' => 20,'subcategoria' => 'Transporte Fluvial e Marítimo']);
        DB::table('subcategoria')->insert(['id_categoria' => 20,'subcategoria' => 'Transporte Rodoviário Coletivo']);
        DB::table('subcategoria')->insert(['id_categoria' => 20,'subcategoria' => 'Transporte Rodoviário de Carga']);
        DB::table('subcategoria')->insert(['id_categoria' => 20,'subcategoria' => 'Transporte Rodoviário de Mudanças']);
        DB::table('subcategoria')->insert(['id_categoria' => 20,'subcategoria' => 'Transporte Rodoviário de Produtos Perigosos']);
        DB::table('subcategoria')->insert(['id_categoria' => 20,'subcategoria' => 'Transportes e Veículos']);
        DB::table('subcategoria')->insert(['id_categoria' => 20,'subcategoria' => 'Vans']);
        DB::table('subcategoria')->insert(['id_categoria' => 20,'subcategoria' => 'UTI Móvel']);
        DB::table('subcategoria')->insert(['id_categoria' => 20,'subcategoria' => 'Metrô']);

        DB::table('subcategoria')->insert(['id_categoria' => 21,'subcategoria' => 'de Itens']);
        DB::table('subcategoria')->insert(['id_categoria' => 21,'subcategoria' => 'de bens']);
        DB::table('subcategoria')->insert(['id_categoria' => 21,'subcategoria' => 'de Caixas']);
        DB::table('subcategoria')->insert(['id_categoria' => 21,'subcategoria' => 'Escolar']);
        DB::table('subcategoria')->insert(['id_categoria' => 21,'subcategoria' => 'de Cartões de Crédito']);
        DB::table('subcategoria')->insert(['id_categoria' => 21,'subcategoria' => 'de Consórcios para Aquisição de Bens e Direitos']);
        DB::table('subcategoria')->insert(['id_categoria' => 21,'subcategoria' => 'de imóveis']);
        DB::table('subcategoria')->insert(['id_categoria' => 21,'subcategoria' => 'de Obras']);
        DB::table('subcategoria')->insert(['id_categoria' => 21,'subcategoria' => 'Pública em Geral']);
        DB::table('subcategoria')->insert(['id_categoria' => 21,'subcategoria' => 'Regionais']);

        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Abracadeiras']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Abrasivos']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Adesivos']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Agenciamento de Cargas']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Antenas']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Aquecedores de água']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Ar comprimido']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Armas e Munições']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Armazéns']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Asilos e Abrigos']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Astrologia']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Bancas de jornais e revistas']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Bibliotecas']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Bicicletárias']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Boliches']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Caçambas']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Carros elétricos']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Corpo de bombeiros']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Delegacias']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Despachantes']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Feiras']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Ferragens']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Filtros']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Floriculturas']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Funerárias']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Gravação de Carimbos']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Guias de turismo']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Guinchos']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Guindastes']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Helicópteros']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Lan Houses']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Lavagem, Lubrificação e Polimento']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Lavanderias']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Mercados municipais']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Mercearias']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Museus']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'ONGs']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Óticas']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Pontos de táxi']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Sauna']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Sebos']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Tatuagens']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Tinturarias']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Torneiros']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Ferro Velho']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Guinchos']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Lava-Rápidos']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Museus']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Antiquários']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Bazares']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Jardinagem']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'carpinteiros']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Outros']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Empregada Doméstica']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Diárista']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Cuidador de Idosos']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Brinquedos']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Presentes']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Fotos']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Filmes/Revelação/Fotos']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Plásticos']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Embalagens']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'PetShopp']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Beleza Animal']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Escolas']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Etec']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Limpeza']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Produtos de Limpeza']);
        DB::table('subcategoria')->insert(['id_categoria' => 22,'subcategoria' => 'Balanças']);

        DB::table('subcategoria')->insert(['id_categoria' => 23,'subcategoria' => 'Cooperativas Centrais de Crédito']);
        DB::table('subcategoria')->insert(['id_categoria' => 23,'subcategoria' => 'Cooperativas Financeiras']);
        DB::table('subcategoria')->insert(['id_categoria' => 23,'subcategoria' => 'Cooperativas Agrícola']);
        DB::table('subcategoria')->insert(['id_categoria' => 23,'subcategoria' => 'Cooperativas de Crédito Mútuo']);

        DB::table('subcategoria')->insert(['id_categoria' => 24,'subcategoria' => 'Engenharia']);
        DB::table('subcategoria')->insert(['id_categoria' => 24,'subcategoria' => 'Engenheiros Aeronauticos']);
        DB::table('subcategoria')->insert(['id_categoria' => 24,'subcategoria' => 'Engenheiros Agrimensores']);
        DB::table('subcategoria')->insert(['id_categoria' => 24,'subcategoria' => 'Engenheiros Agrônomos']);
        DB::table('subcategoria')->insert(['id_categoria' => 24,'subcategoria' => 'Engenheiros Ambientais']);
        DB::table('subcategoria')->insert(['id_categoria' => 24,'subcategoria' => 'Engenheiros Civis']);
        DB::table('subcategoria')->insert(['id_categoria' => 24,'subcategoria' => 'Engenheiros de Telecomunicações']);
        DB::table('subcategoria')->insert(['id_categoria' => 24,'subcategoria' => 'Engenheiros Eletricistas']);
        DB::table('subcategoria')->insert(['id_categoria' => 24,'subcategoria' => 'Engenheiros Eletrônicos']);
        DB::table('subcategoria')->insert(['id_categoria' => 24,'subcategoria' => 'Engenheiros Florestais']);
        DB::table('subcategoria')->insert(['id_categoria' => 24,'subcategoria' => 'Engenheiros Industriais']);
        DB::table('subcategoria')->insert(['id_categoria' => 24,'subcategoria' => 'Engenheiros Mecânicos']);
        DB::table('subcategoria')->insert(['id_categoria' => 24,'subcategoria' => 'Engenheiros Metalúrgicos']);
        DB::table('subcategoria')->insert(['id_categoria' => 24,'subcategoria' => 'Engenheiros Navais']);
        DB::table('subcategoria')->insert(['id_categoria' => 24,'subcategoria' => 'Engenheiros Quimicos']);
        
        DB::table('subcategoria')->insert(['id_categoria' => 25,'subcategoria' => 'Exercito']);
        DB::table('subcategoria')->insert(['id_categoria' => 25,'subcategoria' => 'Escritório']);
        DB::table('subcategoria')->insert(['id_categoria' => 25,'subcategoria' => 'Móveis']);
        DB::table('subcategoria')->insert(['id_categoria' => 25,'subcategoria' => 'Decoração']);
        DB::table('subcategoria')->insert(['id_categoria' => 25,'subcategoria' => 'Cama, Mesa e Banho']);
        DB::table('subcategoria')->insert(['id_categoria' => 25,'subcategoria' => 'Utilitários para Escritório']);
        DB::table('subcategoria')->insert(['id_categoria' => 25,'subcategoria' => 'Show Room Interiores']);
        DB::table('subcategoria')->insert(['id_categoria' => 25,'subcategoria' => 'Sofa']);
        DB::table('subcategoria')->insert(['id_categoria' => 25,'subcategoria' => 'Cama']);
        DB::table('subcategoria')->insert(['id_categoria' => 25,'subcategoria' => 'Loja de Móveis e Decoração']);
        DB::table('subcategoria')->insert(['id_categoria' => 25,'subcategoria' => 'Utilidades Domésticas']);
        DB::table('subcategoria')->insert(['id_categoria' => 25,'subcategoria' => 'Design de Interiores']);
        DB::table('subcategoria')->insert(['id_categoria' => 25,'subcategoria' => 'Móveis para Escritório']);
        DB::table('subcategoria')->insert(['id_categoria' => 25,'subcategoria' => 'Produtos elétricos']);

        DB::table('subcategoria')->insert(['id_categoria' => 26,'subcategoria' => 'Cursos Profissionalizantes']);
        DB::table('subcategoria')->insert(['id_categoria' => 26,'subcategoria' => 'Etec']);
        DB::table('subcategoria')->insert(['id_categoria' => 26,'subcategoria' => 'Fatec']);
        DB::table('subcategoria')->insert(['id_categoria' => 26,'subcategoria' => 'Faculdades']);
        DB::table('subcategoria')->insert(['id_categoria' => 26,'subcategoria' => 'Cursos de Idiomas']);
        DB::table('subcategoria')->insert(['id_categoria' => 26,'subcategoria' => 'Cursos de Informática']);
        DB::table('subcategoria')->insert(['id_categoria' => 26,'subcategoria' => 'Escolas de Informática']);
        DB::table('subcategoria')->insert(['id_categoria' => 26,'subcategoria' => 'Cursos de Vestibulinho']);
        DB::table('subcategoria')->insert(['id_categoria' => 26,'subcategoria' => 'Cursos de Vestibular']);
        DB::table('subcategoria')->insert(['id_categoria' => 26,'subcategoria' => 'Escolas de Segunda Grau']);
        DB::table('subcategoria')->insert(['id_categoria' => 26,'subcategoria' => 'Escolas de Ensino Superior']);
        DB::table('subcategoria')->insert(['id_categoria' => 26,'subcategoria' => 'Escolas Infantil']);

        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Delegacias']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Prefeitura']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Forum']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Ministérios']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Cemiterios']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Cartório']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Rodoviaria']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Hospitais Publicos']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Escolas Publicas']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Transporte Público']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Limpeza Pública']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Esportes']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'ONG`s']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Museus']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'IBGE']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Asilo']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Controle de Vetores']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Zonooses']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Etec']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Fatec']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Poupa Tempo']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Sesi']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Bombeiros']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Militares']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Rede de Água']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Sindicatos']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Creches']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Biblioteca']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Postos de Saúde']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Saneamento Básico']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Coleta de lixo']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Ciretran']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Detran']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'INSS']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Receita Federal']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Correios']);
        DB::table('subcategoria')->insert(['id_categoria' => 27,'subcategoria' => 'Albergue']);

        DB::table('subcategoria')->insert(['id_categoria' => 28,'subcategoria' => 'Delegacias']);
        DB::table('subcategoria')->insert(['id_categoria' => 28,'subcategoria' => 'Prefeitura']);
        DB::table('subcategoria')->insert(['id_categoria' => 28,'subcategoria' => 'Forum']);
        DB::table('subcategoria')->insert(['id_categoria' => 28,'subcategoria' => 'Ministérios']);
        DB::table('subcategoria')->insert(['id_categoria' => 28,'subcategoria' => 'Cemiterios']);
        DB::table('subcategoria')->insert(['id_categoria' => 28,'subcategoria' => 'Cartório']);
        DB::table('subcategoria')->insert(['id_categoria' => 28,'subcategoria' => 'Rodoviaria']);
        DB::table('subcategoria')->insert(['id_categoria' => 28,'subcategoria' => 'Hospitais Publicos']);
        DB::table('subcategoria')->insert(['id_categoria' => 28,'subcategoria' => 'Escolas Publicas']);
        DB::table('subcategoria')->insert(['id_categoria' => 28,'subcategoria' => 'Transporte Público']);
        DB::table('subcategoria')->insert(['id_categoria' => 28,'subcategoria' => 'Limpeza Pública']);
        DB::table('subcategoria')->insert(['id_categoria' => 28,'subcategoria' => 'Esportes']);
        DB::table('subcategoria')->insert(['id_categoria' => 28,'subcategoria' => 'ONG`s']);
        DB::table('subcategoria')->insert(['id_categoria' => 28,'subcategoria' => 'Museus']);
        DB::table('subcategoria')->insert(['id_categoria' => 28,'subcategoria' => 'IBGE']);
        DB::table('subcategoria')->insert(['id_categoria' => 28,'subcategoria' => 'Asilo']);
        DB::table('subcategoria')->insert(['id_categoria' => 28,'subcategoria' => 'Controle de Vetores']);
       
    }
}


